# Generated by Django 6.0.4 on 2026-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_remove_role_permissions_memberrole_granted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Automatically assigned to new invites."
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="Cannot be deleted or modified by users."
            ),
        ),
    ]
