# Generated by Django 6.0.4 on 2026-04-20 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sso_enforced",
                    models.BooleanField(
                        default=False, help_text="Require SAML/SSO login"
                    ),
                ),
                (
                    "mfa_required",
                    models.BooleanField(
                        default=False,
                        help_text="Require Multi-Factor Authentication for all members",
                    ),
                ),
                (
                    "fiscal_year_start_month",
                    models.IntegerField(
                        default=1, help_text="1 for Jan, 4 for Apr, etc."
                    ),
                ),
                ("default_timezone", models.CharField(default="UTC", max_length=50)),
                ("custom_ui_config", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
